### PR TITLE
well-format JSON output would be great

### PR DESCRIPTION
**Pull request by yorkie**

### CODE REVIEW

**Comment by yorkie** [comment]
ping @paulomcnally.

**Comment by paulomcnally** [comment]
timeout hahaha. Sorry.

**Comment by paulomcnally** [comment]
Done:
https://github.com/paulomcnally/json-api-response/releases/tag/v1.0.0

Check documentation: https://github.com/paulomcnally/json-api-response/blob/master/README.md

Thanks

**Comment by yorkie** [comment]
:p

**Pull request merged**
